def CountNucleotides(DNA):
    nucleotides = []
    for i in range(len(DNA)):
        nucleotides.append(DNA[i])
    A_count = 0
    C_count = 0
    G_count = 0
    T_count = 0
    for x in nucleotides:
        if x == "A":
            A_count += 1
        elif x == "C":
            C_count += 1
        elif x == "G":
            G_count += 1
        else:
            T_count += 1
    print A_count, C_count, G_count, T_count

CountNucleotides("TTTCACCAGTCTCACTTCGGGAAAACCGACTCGGCGGAAATGGGAGAATCGTGACTCACACAACTTCATGATAACCGCTAAAGACGATCGGGTTCTGTTCAAATATATGCAACTTGGTTGGGCAGGAGGGGGGTCGTAAAATCATGATGGTAGTGTGGCATATCCCATGCTGGTCTCGAAACGACTCCAATCCCATTCACGTCGTGGTGTCCCGTAACGAGAGAGCCGGCGTTTCATCATGTGAAAAAATTATGCGGTTGCAATGAACTACTATGTTAAGGTTGAAGCTGAGCCTCGCCATAGTTGCGTCCTCGCTTAAAGTGATCAGAAGAGTTCATCGGACAGTTAGTTTTCCCCTAGTCCTTTCCGTCATATATGCCTTTACATAGATGGACCGAGCCAATGAGTGCAGGTCTCAGAGCGCCGGATCCAGGCGTCCACTTGGCCCTGTAGGTGCCGTTGAGAGACGACGCGTTCAGACGATCACAACCATTACGGTGGGCGCTTTACTATCGCGGCAGTAATACCCTTATGGGGCTACAACGCATCTCTTCAAGATGATCCCCAACGGGAACTCCGAATCAGTGATAAGGTGAGTGCAGATGCTTACCATCTCTAGTAGATCCGCGTGCCTCTGGGAGCGAGTACACCCGTACGTCGGGCCCACCATCGGTTGCAACAAATCCTGCTAACGGGCACAACCCAGTTTAAGCCTGTCTCATCAGTCTACCTCTACCCGCTCAGCCTGCGACTTGGGTGTGGGCCCATACAGTAACGTATCTATTGAGTAATATCTAGCAAGTAACAATACCTTCCTTCCAAGAGGGCACACATTGGGCGAGTTTAGAAAAGTCAGAGATGTTTGCAGAAGGGTCG")
